### ISSUE TITLE
Unable to detect rhyming for pony and bologna

### ISSUE THREAD

**Issue by gunthercox** [kevin-brown/rhyme-detect#2]
For the words _pony_ and _bologna_, `word_similarity` returns 0.

```
rhymes.word_similarity("pony", "bologna")
>>> 0
```

**Comment by kevin-brown** [comment]
I can't reproduce this

``` python
>>> word_similarity("pony", "bologna")
0.8333333333333334
```

Keep in mind that if you misspell "bologna", the result will always be zero because we were not able to find set of phones for the word.
